# Generated by Django 3.2.8 on 2021-11-21 06:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0002_auto_20211115_0606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='like_item',
        ),
        migrations.RemoveField(
            model_name='inbox',
            name='post_item',
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbox_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), default=list, size=None),
        ),
    ]
