# Generated by Django 3.2.8 on 2021-11-22 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0003_auto_20211121_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='inbox_items',
            new_name='items',
        ),
    ]
