# Generated by Django 3.2.8 on 2021-11-22 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0005_alter_inbox_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='author',
            new_name='inbox_author',
        ),
    ]
