# Generated by Django 3.2.8 on 2021-10-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='5ebfcf01f5494fd39e317dfacac5b027', max_length=255, primary_key=True, serialize=False),
        ),
    ]
