# Generated by Django 3.2.8 on 2021-10-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='9f6ffe6e87a84971ae40e8f05693f9ef', max_length=255, primary_key=True, serialize=False),
        ),
    ]
