# Generated by Django 3.2.8 on 2021-10-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='7d424b417e734bf487ed623035afd538', max_length=255, primary_key=True, serialize=False),
        ),
    ]
