# Generated by Django 3.2.8 on 2021-10-29 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='1e86ae0af23844bfb4d55145d638ec10', max_length=255, primary_key=True, serialize=False),
        ),
    ]
