# Generated by Django 3.2.8 on 2021-10-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='b68ac9dec0ec404e80c773dcaddd659b', max_length=255, primary_key=True, serialize=False),
        ),
    ]
