# Generated by Django 3.2.8 on 2021-11-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='8ba11a1d7af64f7b8aa0375206b40026', max_length=255, primary_key=True, serialize=False),
        ),
    ]
