# Generated by Django 3.2.8 on 2021-10-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='8b77503cef97497a8f9c56c10d21d20a', max_length=255, primary_key=True, serialize=False),
        ),
    ]
