# Generated by Django 3.2.8 on 2021-10-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='932feab9f5f14af49e36b42327201c09', max_length=255, primary_key=True, serialize=False),
        ),
    ]
