# Generated by Django 3.2.8 on 2021-11-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='155e2c1cffac4f6e8b4fc81c93e2d17c', max_length=255, primary_key=True, serialize=False),
        ),
    ]
