# Generated by Django 3.2.8 on 2021-10-28 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20211028_0645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='postType',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.URLField(),
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.AddField(
            model_name='categories',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
        migrations.AlterUniqueTogether(
            name='categories',
            unique_together={('id', 'post')},
        ),
    ]
