# Generated by Django 3.2.8 on 2021-10-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='db4387f2898c46a1bcaf9cb43bd8ade4', max_length=255, primary_key=True, serialize=False),
        ),
    ]
