# Generated by Django 3.2.8 on 2021-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='44cfb2f34a8d4a509db438d79b935d4f', max_length=255, primary_key=True, serialize=False),
        ),
    ]
