# Generated by Django 3.2.8 on 2021-10-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='45c000cddf5d46ce92cc6293f83f7a6a', max_length=255, primary_key=True, serialize=False),
        ),
    ]
