# Generated by Django 3.2.8 on 2021-10-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='8f350fb8dc354054b7b41564af4973c6', max_length=255, primary_key=True, serialize=False),
        ),
    ]
