# Generated by Django 3.2.8 on 2021-10-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='88bce2631de540c6aa32e4abc1ad7590', max_length=255, primary_key=True, serialize=False),
        ),
    ]
