# Generated by Django 3.2.8 on 2021-10-28 21:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_auto_20211028_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='post',
            name='type',
            field=models.CharField(default='post', max_length=255),
        ),
    ]
