# Generated by Django 3.2.8 on 2021-10-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='795fd75c553d4a7da781f7165eb82418', max_length=255, primary_key=True, serialize=False),
        ),
    ]
