# Generated by Django 3.2.8 on 2021-10-29 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='8271fe41f14b4ed2be67950ae0212eaf', max_length=255, primary_key=True, serialize=False),
        ),
    ]
