# Generated by Django 3.2.8 on 2021-11-23 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0008_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='origin',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='post',
            name='source',
            field=models.CharField(max_length=255),
        ),
    ]
