# Generated by Django 3.2.8 on 2021-10-29 01:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_type'),
        ('post', '0008_auto_20211028_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='post',
            unique_together={('id', 'author')},
        ),
    ]
