# Generated by Django 3.2.8 on 2021-10-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='dd86c63e613440c7bf12e4f97dbbe88e', max_length=255, primary_key=True, serialize=False),
        ),
    ]
