# Generated by Django 3.2.8 on 2021-10-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='8b02757bdcca4cfea918264459c913dc', max_length=255, primary_key=True, serialize=False),
        ),
    ]
