# Generated by Django 3.2.8 on 2021-10-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='64f04cd773e44a92a9b3011050f4f6b9', max_length=255, primary_key=True, serialize=False),
        ),
    ]
