# Generated by Django 3.2.8 on 2021-10-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='08401a0cede941209a1b9cbfa7f441f8', max_length=255, primary_key=True, serialize=False),
        ),
    ]
