# Generated by Django 3.2.8 on 2021-10-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0012_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.CharField(default='8b116fd9a694450cbd2d1b824160e2b6', max_length=255, primary_key=True, serialize=False),
        ),
    ]
