# Generated by Django 3.2.8 on 2021-10-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2021-10-18T21:40:04-06:00'),
        ),
    ]
