# Generated by Django 3.2.8 on 2021-10-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_comment_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2021-10-19T00:15:21-06:00'),
        ),
    ]
