# Generated by Django 3.2.8 on 2021-10-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_comment_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2021-10-19T12:43:18-06:00'),
        ),
    ]
