# Generated by Django 3.2.8 on 2021-10-23 22:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_inbox'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inbox',
            name='id',
        ),
        migrations.AddField(
            model_name='inbox',
            name='inbox_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
