# Generated by Django 3.2.8 on 2021-10-20 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_comment_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='contentType',
            field=models.CharField(default='text/markdown', max_length=255),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2021-10-19T19:45:05-06:00'),
        ),
    ]
