# Generated by Django 3.2.8 on 2021-10-20 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20211019_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.post'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='published',
            field=models.DateTimeField(default='2021-10-19T19:58:39-06:00'),
        ),
    ]
