# Generated by Django 3.2.8 on 2021-10-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='uuid',
        ),
        migrations.AddField(
            model_name='like',
            name='id',
            field=models.CharField(default='472b73ec4d1f4da3b045502673e0b961', max_length=255, primary_key=True, serialize=False),
        ),
    ]
