# Generated by Django 3.2.8 on 2021-10-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='fbf9ce7db0c149daa79b01e1d61d5c5f', max_length=255, primary_key=True, serialize=False),
        ),
    ]
