# Generated by Django 3.2.8 on 2021-10-29 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='1309896c2cdb4658be383b128f602c2b', max_length=255, primary_key=True, serialize=False),
        ),
    ]
