# Generated by Django 3.2.8 on 2021-10-29 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='48a9426278114eecbd68202f3e3487cc', max_length=255, primary_key=True, serialize=False),
        ),
    ]
