# Generated by Django 3.2.8 on 2021-10-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='202285f3d1e244a4808dc1ddaedd7270', max_length=255, primary_key=True, serialize=False),
        ),
    ]
