# Generated by Django 3.2.8 on 2021-10-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='4e7c7a6e221145219972bc81ad85628b', max_length=255, primary_key=True, serialize=False),
        ),
    ]
