# Generated by Django 3.2.8 on 2021-10-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0002_auto_20211029_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='e3195f55740f48b9bc6933f6d236ac96', max_length=255, primary_key=True, serialize=False),
        ),
    ]
