# Generated by Django 3.2.8 on 2021-11-15 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0003_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='76ca1301029b460f90929b3da13f7d42', max_length=255, primary_key=True, serialize=False),
        ),
    ]
