# Generated by Django 3.2.8 on 2021-11-15 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0004_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='d72d17e8b01d45978546b75a7316ddf7', max_length=255, primary_key=True, serialize=False),
        ),
    ]
