# Generated by Django 3.2.8 on 2021-10-29 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_alter_comment_id'),
        ('post', '0010_alter_post_id'),
        ('likes', '0004_alter_like_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='type',
            field=models.CharField(default='Like', max_length=255),
        ),
        migrations.AlterField(
            model_name='like',
            name='comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='comment.comment'),
        ),
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='559aca6eddf04e189cd0a956e36c5c0a', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='like',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.post'),
        ),
    ]
