# Generated by Django 3.2.8 on 2021-10-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_alter_author_url'),
        ('post', '0011_alter_post_id'),
        ('comment', '0008_alter_comment_id'),
        ('likes', '0005_auto_20211029_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='55524be2fe8a4b92aae044726c9e345a', max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('author', 'post'), ('author', 'comment')},
        ),
    ]
