# Generated by Django 3.2.8 on 2021-10-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0006_auto_20211029_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(default='2448273406e047fcbc75ec9f6fe00eb1', max_length=255, primary_key=True, serialize=False),
        ),
    ]
