# Generated by Django 3.2.8 on 2021-11-15 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0006_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
