# Generated by Django 3.2.8 on 2021-11-23 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0007_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('66a793c6-7432-4a38-a379-d9a33626c095'), primary_key=True, serialize=False),
        ),
    ]
