# Generated by Django 3.2.8 on 2021-11-23 04:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0008_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(default=uuid.UUID('80dcb5a4-27b4-4123-b864-885a64b041c7'), primary_key=True, serialize=False),
        ),
    ]
