# Generated by Django 3.2.8 on 2021-11-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0009_alter_like_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
