# Generated by Django 3.2.8 on 2021-10-26 23:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('type', models.CharField(max_length=255)),
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('host', models.CharField(max_length=255)),
                ('displayName', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=255)),
                ('profileImage', models.CharField(max_length=255)),
                ('uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
