# Generated by Django 3.2.8 on 2021-10-19 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='githubLink',
            new_name='github',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='profileImageLink',
            new_name='profileImage',
        ),
    ]
