# Generated by Django 3.2.8 on 2021-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_auto_20211019_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.URLField(primary_key=True, serialize=False),
        ),
    ]
