# Generated by Django 3.2.8 on 2021-11-19 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='is_active',
        ),
    ]
