# Generated by Django 3.2.8 on 2021-10-29 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='host',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='author',
            name='url',
            field=models.URLField(default='<django.db.models.fields.URLField>/author/<django.db.models.fields.CharField>'),
        ),
    ]
