# Generated by Django 3.2.8 on 2021-10-23 22:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0002_auto_20211023_2203'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('author_id', 'follower_id')},
        ),
    ]
