# Generated by Django 3.2.8 on 2021-10-24 04:29

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0003_alter_followers_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='followers',
            name='follow_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='followers',
            name='follower_url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.URLField(default=''),
        ),
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('author_id', 'follower_url')},
        ),
        migrations.RemoveField(
            model_name='followers',
            name='follower_id',
        ),
    ]
