# Generated by Django 3.2.8 on 2021-10-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0004_auto_20211024_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower_url',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.URLField(),
        ),
    ]
