# Generated by Django 3.2.8 on 2021-10-24 04:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0005_auto_20211024_0429'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='followers',
            unique_together={('author_id', 'id'), ('author_id', 'follower_url')},
        ),
    ]
