# Generated by Django 3.2.8 on 2021-10-24 04:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0007_alter_friendrequest_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendrequest',
            name='request_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
