# Generated by Django 3.2.8 on 2021-10-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0008_friendrequest_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='actor',
            field=models.URLField(),
        ),
    ]
