# Generated by Django 3.2.8 on 2021-10-24 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_id'),
        ('followers', '0009_alter_friendrequest_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_id', to='author.author'),
        ),
    ]
