# Generated by Django 3.2.8 on 2021-10-25 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0010_alter_followers_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='follower_url',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='actor',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.JSONField(),
        ),
    ]
