# Generated by Django 3.2.8 on 2021-10-25 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_auto_20211024_0605'),
        ('followers', '0011_auto_20211025_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followers',
            name='author_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author'),
        ),
        migrations.AlterField(
            model_name='followers',
            name='follower_url',
            field=models.URLField(),
        ),
    ]
