# Generated by Django 3.2.8 on 2021-10-29 21:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        ('post', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.CharField(default='a3ed9f2d7b1147bb9f452a5117a34cff', editable=False, max_length=255, primary_key=True, serialize=False)),
                ('type', models.CharField(default='comment', max_length=255)),
                ('comment', models.TextField()),
                ('contentType', models.CharField(default='text/markdown', max_length=255)),
                ('published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.post')),
            ],
        ),
    ]
