# Generated by Django 3.2.8 on 2021-10-29 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='ca36c5b854e943e1b37994fd9fc80951', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
