# Generated by Django 3.2.8 on 2021-10-29 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='1eb1308f5ca549168a5a7ea922c37220', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
