# Generated by Django 3.2.8 on 2021-10-29 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_alter_author_url'),
        ('comment', '0002_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='author.author'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='72e82fe149264949bad4f0576c52affa', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
