# Generated by Django 3.2.8 on 2021-10-28 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_rename_uuid_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='commentType',
            new_name='type',
        ),
    ]
