# Generated by Django 3.2.8 on 2021-10-29 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_id'),
        ('comment', '0003_auto_20211029_2158'),
    ]

    operations = [
    ]
