# Generated by Django 3.2.8 on 2021-10-29 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='31ec9f26627e402ebae18b871963d0ed', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
