# Generated by Django 3.2.8 on 2021-10-29 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20211029_1853'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='author',
            new_name='comment_author',
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='f8fc9b1416424f4a81bd5930202706d9', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
