# Generated by Django 3.2.8 on 2021-10-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='6c6478c08802427b95da9d2766e33e30', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
