# Generated by Django 3.2.8 on 2021-10-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_merge_0003_alter_comment_id_0003_auto_20211029_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='6e42ad28c2834ec5adf12cbbdb1fc9f1', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
