# Generated by Django 3.2.8 on 2021-10-29 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_alter_author_url'),
        ('comment', '0004_auto_20211029_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_author',
        ),
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='author.author'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='2798b0fbc0184dfcbf12b57c2e6d945a', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
