# Generated by Django 3.2.8 on 2021-10-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='070f20077b4b4f2d918f16cbdf48eb12', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
