# Generated by Django 3.2.8 on 2021-10-29 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0004_alter_comment_id'),
        ('comment', '0005_auto_20211029_1859'),
    ]

    operations = [
    ]
