# Generated by Django 3.2.8 on 2021-10-29 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_merge_0004_alter_comment_id_0005_auto_20211029_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='b21299fcc5bc4531971a62b5224aa6f8', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
