# Generated by Django 3.2.8 on 2021-10-29 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0006_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='48f0e3c37d464578ad0ca3f52d78b42e', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
