# Generated by Django 3.2.8 on 2021-11-15 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='4b28d21b11e44002a53800c3c08d3a40', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
