# Generated by Django 3.2.8 on 2021-10-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='ea646e37aeba4c1cb259483952858fbe', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
