# Generated by Django 3.2.8 on 2021-10-29 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0007_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='bd2912534f6b4739b94163923b8008e1', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
