# Generated by Django 3.2.8 on 2021-10-29 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='54ecd69f4c5542b0ba632eed226ef128', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
