# Generated by Django 3.2.8 on 2021-10-29 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0008_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='b7f2acb3956149b49097c6f28b2945a5', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
