# Generated by Django 3.2.8 on 2021-10-29 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0010_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(default='5c0da5bd3ba34034b0b943fc50b6cdf6', editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
