# Generated by Django 3.2.8 on 2021-11-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0012_alter_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='id',
            field=models.CharField(max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
